Ensure State is a known dialect when checking `State.isHeaderState` (#332)
* Test case to illustrate exception

```
io.xlate.edi.stream.EDIStreamException: Invalid X12 ISA segment: too short or elements missing
 at io.xlate.edi.internal.stream.StaEDIStreamWriter.writeEndSegment(StaEDIStreamWriter.java:549)
 at io.xlate.edi.internal.stream.StaEDIStreamWriterTest.writeFromReader(StaEDIStreamWriterTest.java:757)
 at io.xlate.edi.internal.stream.StaEDIStreamWriterTest.testInputEquivalence(StaEDIStreamWriterTest.java:717)
```

* Ensure State is a known dialect when checking `State.isHeaderState`

Signed-off-by: Michael Edgar <michael@xlate.io>

---------

Signed-off-by: Michael Edgar <michael@xlate.io>
Co-authored-by: Michael Edgar <michael@xlate.io>